<ul>
	<li><a href="form_greve.php">Cadastre a Greve</a></li>|
	<li><a href="form_cadastro.php">Cadastro de Pessoas</a></li>|
	<li><a href="form_opiniao.php">Dê sua Opinião</a></li>|
    <li><a href="form_efeitos.php">Consequências da Greve</a></li>|
	<li><a href="listagem_greve.php">Lista de Greves</a></li>|
	<li><a href="listagem_pessoas.php">Lista de Pessoas</a></li>|
	<li><a href="listagem_opiniao.php">Lista de Opiniões</a></li>|
	<li><a href="listagem_efeitos.php">Lista de Consequências</a></li>
 </ul>
 
 
 
 